MAINTAINER Red Hat Training <training@redhat.com>

# DocumentRoot for Apache
ENV DOCROOT=/var/www/html 

RUN   yum ie root user
USER root nstall -y --no-docs --disableplugin=subscription-manager httpd && \ 
      yum clean all --disableplugin=subscription-manager -y && \
      echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html

# Allows child images to inject their own content into DocumentRoot
ONBUILD COPY src/ ${DOCROOT}/ 

EXPOSE 80

# This s thtuff is needed to ensure a clean start
RUN rm -rf /run/httpd && mkdir /run/httpd

# Run as 
USER root 

# Launch httpd
CMD /usr/sbin/httpd -DFOREGROUND
